# Site settings
title: Your awesome title
email: your-email@domain.com
description: ""
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: redcarpet
permalink: pretty

exclude:
  - '*.haml'
  - 'bower_components'
  - 'node_modules'
  - '*.rb'
  - '*.coffee'
  - 'Guardfile'
  - 'Procfile'
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.yml'
  - 'app'
  - 'bower.json'
  - 'package.json'
  - 'Gruntfile.coffee'
  - '.fontcustom-manifest.json'


defaults:
  values:
    layout: "default"